// Generated by CoffeeScript 1.6.3
(function() {
  var Seq, fs, jade, resultFile, resultFileName, resultTemplate, routes, templatesPath, testsFile, testsFileName, testsTemplate;

  Seq = require('seq');

  jade = require('jade');

  fs = require('fs');

  templatesPath = ("" + __dirname + "/templates").replace('dist', 'src');

  testsFileName = "" + templatesPath + "/tests.jade";

  testsFile = fs.readFileSync(testsFileName, {
    encoding: 'utf8'
  });

  testsTemplate = jade.compile(testsFile, {
    filename: testsFileName,
    pretty: true
  });

  resultFileName = "" + templatesPath + "/result.jade";

  resultFile = fs.readFileSync(resultFileName, {
    encoding: 'utf8'
  });

  resultTemplate = jade.compile(resultFile, {
    filename: resultFileName,
    pretty: true
  });

  routes = function(app, manager) {
    var rootPath;
    rootPath = manager._config.rootPath;
    app.get("" + rootPath, function(req, res) {
      var html, payload;
      payload = {
        options: {
          rootPath: manager._config.rootPath
        },
        tests: manager.list()
      };
      html = testsTemplate(payload);
      return res.send(200, html);
    });
    return app.get("" + rootPath + "/results/:name", function(req, res) {
      var name;
      name = req.params.name;
      return Seq().seq(function() {
        return manager.execute(name, this);
      }).seq(function(result) {
        var html, payload;
        payload = {
          options: {
            rootPath: manager._config.rootPath
          },
          result: result,
          test: name
        };
        html = resultTemplate(payload);
        return res.send(200, html);
      });
    });
  };

  module.exports = routes;

}).call(this);
